name: get
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://akilar.top/ -o akilar.top.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://mrnobody233.github.io/ -o mrnobody233.github.io.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://thirsty-c.github.io/ -o thirsty-c.github.io.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://charxd.netlify.app/ -o charxd.netlify.app.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://P-luminary.github.io/ -o P-luminary.github.io.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.youtube.com/ -o www.youtube.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.bilibili.com/ -o www.bilibili.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://picrew.me/ -o picrew.me.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://twitter.com/ -o twitter.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.pixiv.net/ -o www.pixiv.net.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/http://www.xfcdm.com/ -o www.xfcdm.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.hwjyingshi.xyz/ -o www.hwjyingshi.xyz.jpg

        curl https://purge.jsdelivr.net/gh/fish214057/ScreenShot@gh-pages/*.*
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
